#!/usr/bin/env ruby

# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# Find the sum of all the even-valued terms in the sequence which do not
# exceed four million.

# http://projecteuler.net/index.php?section=problems&id=2

sum = 2
prev1 = 1
prev2 = 2
new_term = 0
while new_term < 4_000_000
  new_term = prev1 + prev2
  prev1 = prev2
  prev2 = new_term
  sum += new_term if new_term.even?
  #puts "term: #{prev2} sum: #{sum}"
end
puts sum
